recipe:
  materials:
    G: GLASS
    I: IRON_BLOCK
    N: NETHER_STAR
    D: DIAMOND
  pattern:
    - GIG
    - DND
    - GIG

item:
  type: LODESTONE
  name: '#008DDAChunk Loader'
  lore:
    - '#7F7F7FPlace this item to load the'
    - '#7F7F7Fchunk it is placed in. This'
    - '#7F7F7Fwill keep the chunk loaded.'